import type { CSSProperties } from "react";

/** Co-located styles for ConventionCandidateCard. */
export const s = {
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    borderRadius: 8,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderWidth: 1,
    borderLeftWidth: 3,
    borderLeftColor: accepted ? "var(--ok)" : rejected ? "var(--text-muted)" : "var(--border-strong)",
    background: "var(--bg-elevated)",
    padding: "18px 22px",
    opacity: rejected ? 0.6 : 1,
    transition: "opacity .2s, border-color .12s",
  }),
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 24 } satisfies CSSProperties,
  titleCol: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  titleRow: { display: "flex" } satisfies CSSProperties,
  title: {
    fontSize: 14.5,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  ruleInput: {
    flex: 1,
    minWidth: 200,
    fontSize: 14.5,
    fontWeight: 600,
    fontStyle: "italic",
    color: "var(--text-primary)",
    background: "var(--bg-hover)",
    border: "1px solid var(--border-strong)",
    borderRadius: 5,
    padding: "3px 7px",
    outline: "none",
  } satisfies CSSProperties,
  metaRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  category: { fontSize: 12, color: "var(--text-muted)", fontWeight: 500 } satisfies CSSProperties,
  actions: { display: "flex", flexDirection: "column", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  codeBox: {
    marginTop: 18,
    borderRadius: 7,
    border: "1px solid var(--border)",
    overflow: "hidden",
  } satisfies CSSProperties,
  codeBoxHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "9px 14px",
    background: "var(--bg-hover)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "14px 16px",
    background: "var(--bg-canvas, var(--bg-elevated))",
    fontSize: 12.5,
    lineHeight: 1.6,
    color: "var(--text-secondary)",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  confidenceRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
  } satisfies CSSProperties,
  confidenceLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  confidenceBar: { flex: 1, maxWidth: 240 } satisfies CSSProperties,
  confidencePct: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
} as const;
