import type { CSSProperties } from "react";

/** Co-located styles for ConventionCandidateCard. */
export const s = {
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    borderRadius: 8,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderWidth: 1,
    borderLeftWidth: 3,
    borderLeftColor: accepted ? "var(--ok)" : rejected ? "var(--text-muted)" : "var(--border-strong)",
    background: "var(--bg-elevated)",
    padding: "14px 16px",
    opacity: rejected ? 0.6 : 1,
    transition: "opacity .2s, border-color .12s",
  }),
  header: { display: "flex", alignItems: "flex-start", gap: 12 } satisfies CSSProperties,
  titleWrap: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  title: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  ruleInput: {
    flex: 1,
    minWidth: 200,
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    background: "var(--bg-hover)",
    border: "1px solid var(--border-strong)",
    borderRadius: 5,
    padding: "3px 7px",
    outline: "none",
  } satisfies CSSProperties,
  category: { fontSize: 12, color: "var(--text-muted)", fontWeight: 500 } satisfies CSSProperties,
  statusTag: (color: string): CSSProperties => ({ fontSize: 12, fontWeight: 600, color }),
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 6,
  } satisfies CSSProperties,
  snippetWrap: { position: "relative", marginTop: 10 } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "10px 40px 10px 12px",
    borderRadius: 6,
    background: "var(--bg-canvas, var(--bg-hover))",
    border: "1px solid var(--border)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    overflowX: "auto",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  copyBtn: { position: "absolute", top: 6, right: 6 } satisfies CSSProperties,
  confidenceRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
  } satisfies CSSProperties,
  confidenceLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  confidenceBar: { flex: 1, maxWidth: 160 } satisfies CSSProperties,
  confidencePct: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  actions: { display: "flex", gap: 8, marginTop: 12 } satisfies CSSProperties,
} as const;
